console.log("paso 1 cocinar una torta");
console.log("paso 2 prender el horno");
console.log("paso 3 preparar los ingredientes");
console.log("paso 4 colocar ingredientes en un bowl");
console.log("paso 5 batir");
console.log("paso 6 enharinar el molde");
console.log("paso 7 poner mezcla en el molde");
console.log("paso 8 meter molde al horno");
console.log("paso 9 poner cronometro");
console.log("paso 10 meter un cuchillo en la parte de arriba de la torta y fijarse si está hecha");
console.log("paso 11 si la torta está hecha se saca del horno");
console.log("paso 12 apagar el horno");
console.log("paso 13 desmoldar la torta y esperar que enfrie");
console.log("paso 14 poner la torta en un plato y decorar");
console.log("paso 15 comer la torta :)");